/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Encryption;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 *
 * @author Snow
 */
public class Caesar extends javax.swing.JFrame {
    private boolean KeyEnable = false;

    /**
     * Creates new form Caesar
     */
    public Caesar() {
        initComponents();
        LAT.setSelected(true);
        Encrypt.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RunType = new javax.swing.ButtonGroup();
        Language = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Shift = new javax.swing.JTextField();
        CheckBox1 = new javax.swing.JCheckBox();
        key = new javax.swing.JTextField();
        Run = new javax.swing.JButton();
        Encrypt = new javax.swing.JRadioButton();
        Decrypt = new javax.swing.JRadioButton();
        CYR = new javax.swing.JRadioButton();
        LAT = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextField.setColumns(20);
        TextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextField.setRows(5);
        jScrollPane1.setViewportView(TextField);

        jLabel1.setText("Сдвиг:");

        Shift.setText("3");

        CheckBox1.setText("С ключом:");
        CheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox1ActionPerformed(evt);
            }
        });

        key.setEnabled(false);

        Run.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Run.setText("Выполнить");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });

        RunType.add(Encrypt);
        Encrypt.setText("Зашифровать");

        RunType.add(Decrypt);
        Decrypt.setText("Расшифровать");

        Language.add(CYR);
        CYR.setText("Кириллица");

        Language.add(LAT);
        LAT.setText("Латиница");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Encrypt)
                                    .addComponent(Decrypt))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LAT)
                                    .addComponent(CYR))
                                .addGap(18, 18, 18)
                                .addComponent(Run, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Shift, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(key, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Shift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox1)
                    .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Encrypt)
                            .addComponent(CYR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Decrypt)
                            .addComponent(LAT)))
                    .addComponent(Run, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        if(TextField.getText() != ""){
            short shift = 3; 
            if(Shift.getText() != "") // if shift textbox isn't empty
                shift = Short.parseShort(Shift.getText());
            if(CheckBox1.isSelected() == false){
                if(Encrypt.isSelected()){ //if encrypt choosed
                    if(CYR.isSelected()) //if cyr choosed call encryption method with cyrillic
                        TextField.setText(Encryption.Methods.Caesar(TextField.getText(), shift, "CYR"));
                    else
                        TextField.setText(Encryption.Methods.Caesar(TextField.getText(), shift, "LAT"));
                }else{ //if decryption choosed
                    shift = (short) (shift*-1);
                    if(CYR.isSelected() == true) //if cyr choosed call encryption method with cyrillic
                        TextField.setText(Encryption.Methods.Caesar(TextField.getText(), shift, "CYR"));
                    else
                        TextField.setText(Encryption.Methods.Caesar(TextField.getText(), shift, "LAT"));
                }
            }else{
                if(Encrypt.isSelected()){
                    if(CYR.isSelected())
                        TextField.setText(Encryption.Methods.CaesarKeyEncrypt(TextField.getText(), shift, key.getText(), "CYR"));
                    else
                        TextField.setText(Encryption.Methods.CaesarKeyEncrypt(TextField.getText(), shift, key.getText(), "LAT"));
                }
                else{
                    if(CYR.isSelected())
                        TextField.setText(Encryption.Methods.CaesarKeyDecrypt(TextField.getText(), shift, key.getText(), "CYR"));
                    else
                        TextField.setText(Encryption.Methods.CaesarKeyDecrypt(TextField.getText(), shift, key.getText(), "LAT"));
                }
            }
        }
    }//GEN-LAST:event_RunActionPerformed
    
    private void CheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox1ActionPerformed
        if(KeyEnable == false){
            key.setEnabled(true);
            KeyEnable = true;
        }
        else{
            key.setEnabled(false);
            KeyEnable = false;
        }
    }//GEN-LAST:event_CheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caesar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CYR;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JRadioButton Decrypt;
    private javax.swing.JRadioButton Encrypt;
    private javax.swing.JRadioButton LAT;
    private javax.swing.ButtonGroup Language;
    private javax.swing.JButton Run;
    private javax.swing.ButtonGroup RunType;
    private javax.swing.JTextField Shift;
    private javax.swing.JTextArea TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField key;
    // End of variables declaration//GEN-END:variables
}
